### PR TITLE
Fixed ERD and Schema

### LINKED ISSUE #60: ERD displays wrong type for release date (track)
## *Who* is the bug affecting?

ERD diagram. Needs to be replaced

## *What* is affected by this bug?

Track table, release date is the wrong type

### PR DESCRIPTION
**Pull request by kettle17**
## Description

This PR changes the ERD from feedback and fixes #60 .
The schema has been changed slightly to fit the ERD.

## Motivation and Context

This is required to create the tables and relationships for the database.

## How has this been tested?
Created and connected to a local database and tested running the schema file a few times.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code has a pylint score over 8.5/9.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: pipeline/schema.sql [hunk 1]
```diff
@@ -39,7 +38,7 @@ CREATE TABLE merchandise (
     merchandise_id BIGINT GENERATED ALWAYS AS IDENTITY,
     art_url VARCHAR(255) NOT NULL,
     url VARCHAR(255) NOT NULL,
-    price_at_point_of_sale DECIMAL NOT NULL,
+    sold_for DECIMAL NOT NULL,
```
Comment (context-swtch) [inline pipeline/schema.sql:41]: Much more succinct name for this.

File: pipeline/schema.sql [hunk 2]
```diff
@@ -142,13 +141,22 @@ CREATE TABLE artist_track_assignment (
...
+CREATE TABLE track_tag_assignment (
     tag_assignment_id BIGINT GENERATED ALWAYS AS IDENTITY,
     tag_id BIGINT NOT NULL,
     track_id BIGINT NOT NULL,
     PRIMARY KEY (tag_assignment_id),
     FOREIGN KEY (tag_id) REFERENCES tag (tag_id),
     FOREIGN KEY (track_id) REFERENCES track (track_id)
+);
+
+CREATE TABLE album_tag_assignment (
```
Comment (context-swtch) [inline pipeline/schema.sql:155]: This should make it easier as Dan mentioned, great.

**Review by context-swtch — APPROVED** [review]
